version: "3.3"

networks:
  o11y_e2e:

services:
  o11y_e2e:
    build:
      dockerfile: Dockerfile
    command:
      - --log.level=debug
    networks:
      - o11y_e2e
    ports:
      - 9927:9227
    restart: always
    # TODO: needs syslog connector and config file setup to send logs to otelcol

  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    networks:
      - o11y_e2e
    restart: always

  otelcol:
  # TODO: not positive this works for loki sending but might
    image: otel/opentelemetry-collector-contrib:latest
    volumes:
      - ./docker/otel-collector-config.yml:/etc/otelcol/config.yaml
    ports:
      - "4317:4317" # gRPC receiver port
      - "55681:55681" # OTLP HTTP receiver port
      - "1514:1514" # Syslog receiver port
    networks:
      - o11y_e2e
    depends_on:
      - loki
    restart: always

  prometheus:
    image: prom/prometheus
    volumes:
      - ./docker/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - o11y_e2e
    depends_on:
      - o11y_e2e
    restart: always

  grafana:
      environment:
        - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
        - GF_AUTH_ANONYMOUS_ENABLED=true
        - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      entrypoint:
        - sh
        - -euc
        - |
          mkdir -p /etc/grafana/provisioning/datasources
          cat <<EOF > /etc/grafana/provisioning/datasources/ds.yaml
          apiVersion: 1
          datasources:
          - name: Loki
            type: loki
            access: proxy
            orgId: 1
            url: http://loki:3100
            basicAuth: false
            isDefault: true
            version: 1
            editable: true
          - name: prometheus
            type: prometheus
            access: proxy
            orgId: 1
            url: http://prometheus:9090
            basicAuth: false
            isDefault: false
            version: 1
            editable: true
          EOF
          /run.sh
      image: grafana/grafana:latest
      ports:
        - "3000:3000"
      networks:
      - o11y_e2e
