global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'o11y_e2e'
    metrics_path: '/metrics'
    scrape_interval: 15s
    scrape_timeout: 15s
    static_configs:
      - targets: ["o11y_e2e:9927"]
